name: modapi-launcher-kit

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    env:
      nugetUrl: 'https://dist.nuget.org/win-x86-commandline/latest/nuget.exe'
      modApiUrl: 'https://github.com/emd4600/Spore-ModAPI/releases/latest/download/SporeModAPIdlls.zip'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - name: Install Nuget
        run: |
          Invoke-WebRequest "${env:nugetUrl}" -OutFile nuget.exe
      - name: Prepare Environment
        run: |
          $env:revision = git describe --tags --always
          echo "GIT_REVISION=$env:revision" >> $env:GITHUB_ENV
        shell: pwsh
      - name: Restore Packages
        run: |
          nuget restore
        shell: cmd
      - name: Download latest Spore-ModAPI
        run: |
          Invoke-WebRequest "${env:modApiUrl}" -OutFile SporeModAPIdlls.zip
        shell: pwsh
      - name: Build modapi-launcher-kit
        run: |
          msbuild /p:Configuration=Release
        shell: cmd
      - name: Package ModApiUpdate.zip
        run: |
          "C:\Program Files\7-Zip\7z.exe" e -y SporeModAPIdlls.zip -oOutput\coreLibs
          
          copy LegacyLibs\SporeModAPI-disk.dll Output\SporeModAPI-disk.dll
          copy LegacyLibs\SporeModAPI-steam_patched.dll Output\SporeModAPI-steam_patched.dll

          cd Output
          "C:\Program Files\7-Zip\7z" a -tzip "..\ModApiUpdate.zip" *
        shell: cmd
      - name: Build ModApi.InterimSetup
        run: |
          copy /Y ModApiUpdate.zip ModApi.InterimSetup\ModApi.InterimSetup\Resources\ModApiUpdate.zip

          msbuild ModApi.InterimSetup /p:Configuration=Release
        shell: cmd
      - name: Build ModApi.Updater
        run: |
          copy /Y ModApiUpdate.zip Updater\ModApi.Updater\Resources\ModApiUpdate.zip

          msbuild Updater /p:Configuration=Release
        shell: cmd
      - name: Upload ModApi.InterimSetup
        uses: actions/upload-artifact@v4
        with:
          name: ModApi.InterimSetup-${{ env.GIT_REVISION }}
          path: ModApi.InterimSetup/ModApi.InterimSetup/bin/Release/*.exe
      - name: Upload ModApi.Updater
        uses: actions/upload-artifact@v4
        with:
          name: ModApi.Updater-${{ env.GIT_REVISION }}
          path: Updater/ModApi.Updater/bin/Release/*.exe


