name: modapi-launcher-kit

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    env:
      net40SdkUrl: 'https://www.nuget.org/api/v2/package/Microsoft.NETFramework.ReferenceAssemblies.net40/1.0.3'
      net45SdkUrl: 'https://www.nuget.org/api/v2/package/Microsoft.NETFramework.ReferenceAssemblies.net45/1.0.3'
      sdkSystemPath: 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework'
      nugetUrl: 'https://dist.nuget.org/win-x86-commandline/latest/nuget.exe'
      modApiUrl: 'https://github.com/emd4600/Spore-ModAPI/releases/latest/download/SporeModAPIdlls.zip'

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      # taken from https://github.com/vrnobody/net45action
      - name: Install .NET Framework 4.0 SDK
        run: |
          Invoke-WebRequest -Uri "${env:net40SdkUrl}" -OutFile "${env:temp}\net40sdk.zip"
          Expand-Archive -Force -LiteralPath "${env:temp}\net40sdk.zip" -DestinationPath "${env:temp}\net40sdk"
          [IO.Directory]::Delete("${env:sdkSystemPath}\v4.0", $True)
          Move-Item -Force -LiteralPath "${env:temp}\net40sdk\build\.NETFramework\v4.0" -Destination "${env:sdkSystemPath}"
        shell: pwsh
      - name: Install .NET Framework 4.5 SDK
        run: |
          Invoke-WebRequest -Uri "${env:net45SdkUrl}" -OutFile "${env:temp}\net45sdk.zip"
          Expand-Archive -Force -LiteralPath "${env:temp}\net45sdk.zip" -DestinationPath "${env:temp}\net45sdk"
          [IO.Directory]::Delete("${env:sdkSystemPath}\v4.5", $True)
          Move-Item -Force -LiteralPath "${env:temp}\net45sdk\build\.NETFramework\v4.5" -Destination "${env:sdkSystemPath}"
        shell: pwsh
      - name: Install Nuget
        run: |
          Invoke-WebRequest "${env:nugetUrl}" -OutFile nuget.exe
      - name: Restore Packages
        run: |
          nuget restore
        shell: cmd
      - name: Download latest Spore-ModAPI
        run: |
          Invoke-WebRequest "${env:modApiUrl}" -OutFile SporeModAPIdlls.zip
        shell: pwsh
      - name: Build modapi-launcher-kit
        run: |
          msbuild /p:Configuration=Release
        shell: cmd
      - name: Package ModApiUpdate.zip
        run: |
          "C:\Program Files\7-Zip\7z.exe" e -y SporeModAPIdlls.zip -oOutput\coreLibs
          
          copy LegacyLibs\SporeModAPI-disk.dll Output\SporeModAPI-disk.dll
          copy LegacyLibs\SporeModAPI-steam_patched.dll Output\SporeModAPI-steam_patched.dll

          cd Output
          "C:\Program Files\7-Zip\7z" a -tzip "..\ModApiUpdate.zip" *
        shell: cmd
      - name: Build ModApi.InterimSetup
        run: |
          copy /Y ModApiUpdate.zip ModApi.InterimSetup\ModApi.InterimSetup\Resources\ModApiUpdate.zip

          msbuild ModApi.InterimSetup /p:Configuration=Release
        shell: cmd
      - name: Build ModApi.Updater
        run: |
          copy /Y ModApiUpdate.zip Updater\ModApi.Updater\Resources\ModApiUpdate.zip

          msbuild Updater /p:Configuration=Release
        shell: cmd
      - name: Upload ModApi.InterimSetup
        uses: actions/upload-artifact@v4
        with:
          name: ModApi.InterimSetup
          path: ModApi.InterimSetup/ModApi.InterimSetup/bin/Release/*.exe
      - name: Upload ModApi.Updater
        uses: actions/upload-artifact@v4
        with:
          name: ModApi.Updater
          path: Updater/ModApi.Updater/bin/Release/*.exe


